name: ci-build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        # configuration: [Debug, Release]

    runs-on: windows-latest # For a list of available runner types, refer to
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Set version
      run: |
        dotnet tool install --global GitVersion.Tool --version 5.8.0
        $gitversionInfo = dotnet-gitversion /updateassemblyinfo | ConvertFrom-Json
        $gitversionInfo
        $versionTag = $gitversionInfo.SemVer
        echo "VERSION_TAG=$versionTag" >> $env:GITHUB_ENV

    - name: Run Tests
      run: dotnet test

    - name: Publish App
      run: |
        echo "Version: ${env:VERSION_TAG}"
        dotnet publish .\pick-a-browser\pick-a-browser.csproj -r win10-x64  -p:PublishSingleFile=true -p:PublishTrimmed=false --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -c Release

    - uses: actions/upload-artifact@v2
      with:
        name: pick-a-browser
        path: .\pick-a-browser\bin\Release\net6.0-windows\win10-x64\publish\

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        7z a release.zip .\pick-a-browser\bin\Release\net6.0-windows\win10-x64\publish\*
        gh release create "v${env:VERSION_TAG}" --title "Release ${env:VERSION_TAG}" release.zip
