name: ci-build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        # configuration: [Debug, Release]

    runs-on: windows-latest # For a list of available runner types, refer to
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: "5.5.0"

    - name: Determine version
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Display version
      run: |
        echo "SemVer: $GITVERSION_SEMVER"

    #     # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    #     - name: Setup MSBuild.exe
    #       uses: microsoft/setup-msbuild@v1.0.2

    - name: Run Tests
      run: dotnet test

    - name: Build App
      run: dotnet build --configuration Release  -r win10-x64 /p:AssemblyVersion=$GITVERSION_SEMVER /p:FileVersion=$GITVERSION_ASSEMBLYSEMFILEVER /p:InformationalVersion=$GITVERSION_SEMVER

    - name: Publish App
      run: dotnet publish .\pick-a-browser\pick-a-browser.csproj -r win10-x64  -p:PublishSingleFile=true -p:PublishTrimmed=false --self-contained true -c Release

    - uses: actions/upload-artifact@v2
      with:
        name: pick-a-browser
        path: .\pick-a-browser\bin\Release\net6.0-windows\win10-x64\publish\
